import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {checkStudy,cuesFor,geometry,fileDigest,inputSnapshot,verifySnapshot,inspectVideo} from '../scripts/model.mjs';
import {renderCard,chromeBinary} from '../scripts/cards.mjs';
import {exportStudy,compareAudioTracks} from '../scripts/export.mjs';

const at=process.argv.indexOf('--out');
const work=resolve(at>=0?process.argv[at+1]:'work/aipi-sync-tests');mkdirSync(work,{recursive:true});
const report={schema:'aipi.sync-tests/v1',checks:[],encodedSamples:[]};
const check=(name,fn)=>{fn();report.checks.push(name);};
const video=join(work,'six-frames.mp4');
execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=s=1280x720:r=24:d=0.25','-f','lavfi','-i','sine=frequency=733:sample_rate=48000:duration=0.27','-c:v','libx264','-c:a','aac',video]);
const base={schema:'aipi.film-study/v1',title:'边界回归',source:{file:'six-frames.mp4',width:1280,height:720,fps:24,frameCount:6,duration:.27,videoDuration:.25,hasAudio:true,timing:'cfr',sha256:fileDigest(video)},shots:[['A01',0,2,'第一幅'],['A02',2,3,'只有一帧的第二幅'],['A03',3,6,'第三幅']].map(([id,startFrame,endFrame,description])=>({id,startFrame,endFrame,start:startFrame/24,end:endFrame/24,size:'中景',camera:'固定',transition:'硬切',description,dialogueIds:[],sound:{status:'reviewed',note:'测试音轨已核对。'},director:{intention:'等待回应。',emotion:'从平静到警觉。',blocking:'人物保持同轴。',edit:'动作切换。',reshoot:'保留停顿。'}})),dialogue:[{id:'L1',start:0,end:3/24,text:'这句话跨过切点，必须完整保留。',speaker:'甲',type:'dialogue',source:'audio',status:'verified'},{id:'L2',start:1/24,end:2/24,text:'第二条原话。',speaker:'乙',type:'voiceover',source:'audio',status:'verified'}],review:{audio:{state:'complete',coverage:[{start:0,end:.27,method:'synthetic fixture',notes:'all waveform is known',audioChecked:true}],openIssues:[]},visual:{state:'reviewed'}}};
base.source.duration=Number(JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','json',video],{encoding:'utf8'})).format.duration);
for(const shot of base.shots)shot.dialogueIds=cuesFor(base,shot).map(c=>c.id);
base.shots[2].sound.status='non-speech';base.review.audio.coverage=[{start:0,end:3/24,method:'synthetic fixture',notes:'known cue section',audioChecked:true,result:'speech'},{start:3/24,end:base.source.duration,method:'synthetic fixture',notes:'known non-speech section',audioChecked:true,result:'non-speech'}];
check('complete fixture accepted',()=>assert.equal(checkStudy(base).ok,true));
check('cross-cut text belongs to both exact rows',()=>assert.deepEqual(base.shots.map(s=>s.dialogueIds),[['L1','L2'],['L1'],[]]));
check('missing audio review rejected by default',()=>assert.equal(checkStudy({...base,review:{visual:base.review.visual}}).ok,false));
check('uncertain cue rejected',()=>{const copy=structuredClone(base);copy.dialogue[0].status='uncertain';assert.equal(checkStudy(copy).ok,false);});
check('pending shot rejected',()=>{const copy=structuredClone(base);copy.shots[1].sound.status='pending';assert.equal(checkStudy(copy).ok,false);});
check('OCR-only audio coverage rejected',()=>{const copy=structuredClone(base);copy.review.audio.coverage[0].audioChecked=false;copy.review.audio.coverage[0].subtitlesChecked=true;assert.equal(checkStudy(copy).ok,false);});
check('reference is explicit and retains pending status',()=>{const copy=structuredClone(base);copy.review.audio.state='partial';copy.shots[1].sound.status='pending';assert.equal(checkStudy(copy,{reference:true}).ok,true);assert.equal(copy.shots[1].sound.status,'pending');});
check('inaccurate seconds rejected without guessing',()=>{const copy=structuredClone(base);copy.shots[1].start=.08;assert.equal(checkStudy(copy,{reference:true}).ok,false);});
check('missing cross-cut reference rejected',()=>{const copy=structuredClone(base);copy.shots[1].dialogueIds=[];assert.equal(checkStudy(copy,{reference:true}).ok,false);});
check('VFR declaration rejected explicitly',()=>assert.equal(checkStudy({...base,source:{...base.source,timing:'vfr'}},{reference:true}).ok,false));
check('nonzero time origin rejected explicitly',()=>assert.equal(checkStudy({...base,source:{...base.source,timeOrigin:1}},{reference:true}).ok,false));
const file=join(work,'study.json');writeFileSync(file,JSON.stringify(base,null,2));
const snapshot=inputSnapshot(file,video,base);writeFileSync(file,JSON.stringify({...base,title:'changed'}));
check('changed input fingerprint rejected',()=>assert.throws(()=>verifySnapshot(snapshot),/已变化/));writeFileSync(file,JSON.stringify(base,null,2));
const chrome=chromeBinary();
const malformed=structuredClone(base);malformed.shots[0].director.reshoot='不可省略的完整中文原文。'.repeat(900);
await assert.rejects(()=>renderCard(malformed,malformed.shots[0],geometry(base.source),{work:join(work,'overflow'),chrome,studyDirectory:work}),/无法完整容纳正文/);report.checks.push('long Chinese text truly overflows and is rejected');
const manifest=await exportStudy({studyFile:file,videoFile:video,outputFile:join(work,'six-frames-review.mp4'),workDirectory:join(work,'landscape'),chrome});
check('six actual encoded source frames retained',()=>assert.equal(Number(manifest.outputProbe.streams.find(s=>s.codec_type==='video').nb_read_frames),6));
check('full audio stream uses original AAC packets',()=>assert.equal(manifest.encoding.audioMode,'original-packets'));
check('output audio duration and sampling parameters were checked',()=>assert.equal(manifest.audioVerification[0].passed,true));
check('shortened output audio is rejected',()=>{const audio=structuredClone(manifest.outputProbe.streams.filter(s=>s.codec_type==='audio'));audio[0].duration=String(Number(audio[0].duration)-.1);assert.throws(()=>compareAudioTracks(manifest.source.audio,audio,'original-packets'),/音轨时长/);});
check('changed output sampling rate is rejected',()=>{const audio=structuredClone(manifest.outputProbe.streams.filter(s=>s.codec_type==='audio'));audio[0].sample_rate='16000';assert.throws(()=>compareAudioTracks(manifest.source.audio,audio,'original-packets'),/采样参数/);});
check('manifest includes start-time implementation fingerprints',()=>{assert.equal(manifest.implementation.length,5);verifySnapshot(manifest.implementation);});
const pcm=file=>execFileSync('ffmpeg',['-v','error','-i',file,'-vn','-f','s16le','-acodec','pcm_s16le','pipe:1'],{maxBuffer:4*1024*1024});
check('decoded source and output audio are byte-identical, including tail',()=>assert.deepEqual(pcm(video),pcm(join(work,'six-frames-review.mp4'))));
const pix=file=>execFileSync('ffmpeg',['-v','error','-i',file,'-pix_fmt','rgb24','-f','rawvideo','pipe:1'],{maxBuffer:64*1024*1024});
const reference=manifest.cards.map(card=>pix(card.file));
const actual=execFileSync('ffmpeg',['-v','error','-i',join(work,'six-frames-review.mp4'),'-vf',`format=rgb24,crop=${manifest.layout.panel.width}:${manifest.layout.panel.height}:0:${manifest.layout.video.height}`,'-pix_fmt','rgb24','-f','rawvideo','pipe:1'],{maxBuffer:64*1024*1024});
const size=manifest.layout.panel.width*manifest.layout.panel.height*3;
for(let frame=0;frame<6;frame++) {
  const pixels=actual.subarray(frame*size,(frame+1)*size);
  const matches=reference.map((ref,index)=>{let total=0;for(let i=0;i<size;i++)total+=(pixels[i]-ref[i])**2;return {id:base.shots[index].id,mse:total/size};}).sort((a,b)=>a.mse-b.mse);
  const expected=base.shots.find(s=>s.startFrame<=frame&&s.endFrame>frame).id;
  assert.equal(matches[0].id,expected);report.encodedSamples.push({frame,expected,actual:matches[0].id,mse:matches[0].mse});
}
report.checks.push('every encoded frame card matches expected shot, including one-frame middle shot');
const tallVideo=join(work,'portrait.mp4');execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=s=720x1280:r=24:d=0.25','-c:v','libx264',tallVideo]);
const tall=structuredClone(base);Object.assign(tall.source,{file:'portrait.mp4',width:720,height:1280,duration:.25,hasAudio:false,sha256:fileDigest(tallVideo)});tall.dialogue=[];for(const shot of tall.shots){shot.dialogueIds=[];shot.sound={status:'non-speech',note:'此测试片无音轨。'};}tall.review.audio={state:'complete',coverage:[],openIssues:[]};
const tallFile=join(work,'portrait.json');writeFileSync(tallFile,JSON.stringify(tall,null,2));const portrait=await exportStudy({studyFile:tallFile,videoFile:tallVideo,outputFile:join(work,'portrait-review.mp4'),workDirectory:join(work,'portrait-render'),chrome});
check('portrait containment and all frames retained',()=>{assert.equal(portrait.layout.orientation,'horizontal-stack');assert.equal(portrait.encoding.writtenFrames,6);assert.ok(Math.abs(portrait.layout.video.width/portrait.layout.video.height-720/1280)<.002);});
const nonzero=join(work,'offset.mp4');execFileSync('ffmpeg',['-v','error','-y','-i',video,'-c','copy','-output_ts_offset','1',nonzero]);
check('actual nonzero PTS rejected',()=>assert.throws(()=>inspectVideo(nonzero,base.source),/零起点/));
const vfr=join(work,'vfr.mp4');execFileSync('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=s=1280x720:r=24:d=0.3','-vf',"select='not(eq(n,2))'",'-fps_mode','vfr','-c:v','libx264',vfr]);
check('actual varying frame intervals rejected',()=>assert.throws(()=>inspectVideo(vfr,base.source),/零起点/));
writeFileSync(join(work,'verification.json'),JSON.stringify(report,null,2)+'\n');
console.log(`PASS ${report.checks.length} independent checks and ${report.encodedSamples.length} encoded first-frame comparisons. ${work}`);
